# Generated by Django 2.1.5 on 2019-02-01 17:26

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5,
                                        primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                 ('TODO', 'todo'), ('DOING', 'Doing'), ('DONE', 'Done')], default='TODO', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(
                    related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
