version: "3.2"
services:
  db:
    image: postgres:11-alpine
    env_file:
      - .env
    networks:
      - db_network
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
  web:
    build: .
    networks:
      - db_network
    volumes:
      - .:/code/
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  db_network:
    driver: bridge

volumes:
  db_volume:
