version: "3.2"
services:
  db:
    image: postgres:11-alpine
    env_file:
      - .env
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/postgresql/data
  web:
    build: .
    networks:
      - db_network
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

networks:
  db_network:
    driver: bridge

volumes:
  db_volume:
    external:
      name: db_volume
